#cspell: words gocom maint autotranslations gsutil webm setmeta gcloud

-include Makefile.passwords

RELEASE=$(shell git describe --long | sed 's@\([0-9.]\{1,\}\).*@\1@')
VERSION=$(shell git describe --long)
OGS_HASH=$(shell md5sum dist/ogs.js | awk '{print $$1}')
OGS_VERSION_HASH=$(VERSION)-$(OGS_HASH)

LANGUAGE_VERSION=`md5sum i18n/locale/*.js | sort | md5sum | awk '{print $$1}'`
SUPPORTED_LANGUAGES=`python -c 'import json; print(json.dumps(json.loads(open("i18n/languages.json", "r").read())))'`

BASE_INDEX_HEADERS=-H "Content-Type: text/plain" \
	-H "X-OGS-Index-Release: $(RELEASE)"  \
	-H "X-OGS-Index-Version: $(VERSION)"  \
	-H "X-OGS-Supported-Languages: $(SUPPORTED_LANGUAGES)"  \
	-H "X-OGS-Language-Version: $(LANGUAGE_VERSION)"  \

DEV_INDEX_HEADERS=$(BASE_INDEX_HEADERS) -H "X-OGS-Index-Auth: $(DEV_INDEX_AUTH)"
BETA_INDEX_HEADERS=$(BASE_INDEX_HEADERS) -H "X-OGS-Index-Auth: $(BETA_INDEX_AUTH)"
PROD_INDEX_HEADERS=$(BASE_INDEX_HEADERS) -H "X-OGS-Index-Auth: $(PROD_INDEX_AUTH)"
	

### Common ### 

## Primary deployment targets
deploy-to-beta: build sync-translations build-i18n create-unified-pot audit-translations jsonify-po-files push-cdn upload-sentry-source-maps save-translation-artifacts
	OGS_VERSION_HASH=$(OGS_VERSION_HASH) npm run minify-index --silent | curl -X PUT $(BETA_INDEX_HEADERS) -d @- https://beta.online-go.com/_index
	make beta-notify-slack

deploy-to-production: load-translation-artifacts build push-cdn
	OGS_VERSION_HASH=$(OGS_VERSION_HASH) npm run minify-index --silent | curl -X PUT $(PROD_INDEX_HEADERS) -d @- https://online-go.com/_index
	make live-notify-slack
	

save-translation-artifacts:	
	cd i18n; scp $(POOTLE_SSH_OPTIONS) locale/*.js $(POOTLE_USER)@$(POOTLE_HOST):artifacts-for-github-actions/locale
	cd i18n; scp $(POOTLE_SSH_OPTIONS) autotranslations.json keys.json languages.json llm-keys-cache.json $(POOTLE_USER)@$(POOTLE_HOST):artifacts-for-github-actions

load-translation-artifacts:	
	@echo "Loading translation artifacts"
	@mkdir -p i18n/locale
	@if [ ! -f i18n/autotranslations.json ]; then \
		cd i18n; \
		scp $(POOTLE_SSH_OPTIONS) $(POOTLE_USER)@$(POOTLE_HOST):'artifacts-for-github-actions/*.json' .; \
		scp $(POOTLE_SSH_OPTIONS) $(POOTLE_USER)@$(POOTLE_HOST):'artifacts-for-github-actions/locale/*.js' locale/; \
	fi


## Helper targets
minify-index:	
	@echo "Testing index minification"
	OGS_VERSION_HASH=$(OGS_VERSION_HASH)  npm run minify-index --silent | wc -c

push: push-cdn

# gsutil -m rsync -r deployment-staging-area/$(RELEASE) gs://ogs-site-files/$(RELEASE)/
# gsutil -m setmeta -h "Content-Type:audio/webm" 'gs://ogs-site-files/$(RELEASE)/sound/*.webm'
push-cdn: prepare-cdn-files
	gcloud storage rsync -r deployment-staging-area/$(RELEASE) gs://ogs-site-files/$(RELEASE)/
	gcloud storage objects update 'gs://ogs-site-files/$(RELEASE)/sound/*.webm' --content-type='audio/webm'

sync-translations: load-translation-artifacts
	mkdir -p i18n/build
	mkdir -p i18n/locale
	cd i18n/build/; ssh $(POOTLE_SSH_OPTIONS) $(POOTLE_USER)@$(POOTLE_HOST) "bash -c 'cd online-go.com/i18n/build; tar jcf - *'" | tar jxf -
	cd i18n/locale/; ssh $(POOTLE_SSH_OPTIONS) $(POOTLE_USER)@$(POOTLE_HOST) "bash -c 'cd online-go.com/i18n/locale; tar jcf - *'" | tar jxf -

create-unified-pot:
	# This is run on the pootle server and here, the pootle server does most of the work,
	# this invocation extracts strings that need to be translated by LLMs
	cd i18n; python  translation-code-replace-for-parsing.py
	cd i18n; node create-unified-pot.js llm-translation-extraction

audit-translations:
	cd i18n; node audit-translations.js

jsonify-po-files:
	cd i18n; node jsonify-po-files.js

prepare-cdn-files: purge-cdn-files dist/ogs.js dist/ogs.min.css
	echo "Language version: $(LANGUAGE_VERSION)"
	mkdir -p deployment-staging-area/$(RELEASE)/
	mkdir -p deployment-staging-area/$(RELEASE)/locale
	cat dist/ogs.js | sed 's/ogs.js.map/ogs.$(OGS_VERSION_HASH).js.map/' > deployment-staging-area/$(RELEASE)/ogs.$(OGS_VERSION_HASH).js
	cp -p dist/ogs.js.map deployment-staging-area/$(RELEASE)/ogs.$(OGS_VERSION_HASH).js.map
	cat dist/ogs.min.css | sed 's/ogs.min.css.map/ogs.min.$(VERSION).css.map/' > deployment-staging-area/$(RELEASE)/ogs.$(VERSION).css
	cp -p dist/ogs.min.css.map deployment-staging-area/$(RELEASE)/ogs.min.$(VERSION).css.map
	cp -Rp assets/img deployment-staging-area/$(RELEASE)/
	cp -Rp assets/sound deployment-staging-area/$(RELEASE)/
	ls i18n/locale/*.js | sed 's@i18n/locale/\([^\.]\+\).js@\1@' | xargs -n1 -I {} cp i18n/locale/{}.js deployment-staging-area/$(RELEASE)/locale/{}.$(LANGUAGE_VERSION).js
	# cleanup
	find deployment-staging-area/ | grep \\.swp$$ | xargs rm -f
	find deployment-staging-area/ | grep "~" | xargs rm -f
	find deployment-staging-area/ | grep /backup/ | xargs rm -f
	find deployment-staging-area/ | grep \\.bak$$ | xargs rm -f
	find deployment-staging-area/ | grep \\.xcf$$ | xargs rm -f
	find deployment-staging-area/ | grep \\.dat$$ | xargs rm -f

upload-sentry-source-maps:
	sentry-cli releases --org online-gocom --project online-gocom new $(VERSION)
	sentry-cli releases --org online-gocom --project online-gocom files $(VERSION) upload-sourcemaps --ignore locale deployment-staging-area/$(RELEASE)/
	sentry-cli releases --org online-gocom --project online-gocom finalize $(VERSION)

purge-cdn-files:
	rm -Rf deployment-staging-area

dist/ogs.$(VERSION).css: dist/ogs.min.css
	cp $< $@ 
	cp $<.map $@.map







### Targets for local development

#dev-put: push-cdn
dev-put:
	OGS_VERSION_HASH=$(OGS_VERSION_HASH) npm run minify-index --silent | curl -X PUT $(DEV_INDEX_HEADERS) -d @- http://localhost:1080/_index

dev-del:
	curl -X DELETE $(DEV_INDEX_HEADERS)  http://localhost:1080/_index

beta-put: deploy-to-beta

live-put: confirm-go-live  deploy-to-production

#live-maint: confirm-go-live 
#	curl -X PUT $(PROD_INDEX_HEADERS) -T src/maint.html  https://online-go.com/_index

beta-notify-slack:
	MSG=`git log -1 --pretty="%B" | sed s/\"//g | sed s/\'//g `; \
	VERSION=`git describe --long`; \
	echo $$VERSION $$MSG; \
	curl -X POST -H 'Content-type: application/json' --data '{"text":"'"[BETA UI] $$VERSION $$MSG"'"}' $(SLACK_WEBHOOK_URL)

live-notify-slack:
	MSG=`git log -1 --pretty="%B" | sed s/\"//g | sed s/\'//g `; \
	VERSION=`git describe --long`; \
	echo $$VERSION $$MSG; \
	curl -X POST -H 'Content-type: application/json' --data '{"text":"'"[PRODUCTION UI] $$VERSION $$MSG"'"}' $(SLACK_WEBHOOK_URL)

confirm-go-live:
	@read -p "Go live? " yesno; \
	test $$yesno == 'yes';



	


.PHONY: dev stats todo update install default server dist push-cdn sync-translations

