# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the devel branch
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules

      - name: Yarn install
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: yarn install

      # Build
      - name: Build CSS
        run: npx gulp min_styl

      - name: Lint
        run: npm run lint

# Uncomment these lines once we have a prettified codebase
#      - name: Prettier
#        run: npm run prettier:check

      - name: Webpack
        run: npx webpack --optimization-minimize --devtool=source-map
        
      - name: Tests
        run: npx jest

      # Log compressed output size
      - name: Compressed sizes
        run: |
          gzip -9 dist/ogs.min.js | wc -c
          gzip -9 dist/vendor.min.js | wc -c
          gzip -9 dist/ogs.min.css | wc -c
    
          
      
