name: CI

on:
    push:
        branches: [devel]
    pull_request:
        branches: [devel]
    workflow_dispatch:

jobs:
    lint:
        uses: ./.github/workflows/lint.yml

    type-check:
        uses: ./.github/workflows/type-check.yml

    build:
        uses: ./.github/workflows/build.yml

    prettier:
        uses: ./.github/workflows/prettier.yml

    spell-check:
        uses: ./.github/workflows/spell-check.yml

    test:
        uses: ./.github/workflows/test.yml
