name: Spell Check
run-name: Spell Check

on:
    push:
        branches: [devel]
    pull_request:
        branches: [devel]
    workflow_dispatch:

jobs:
    run:
        name: Spell check
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
                  lfs: true

            - name: Run spell check
              uses: streetsidesoftware/cspell-action@v6
              with:
                  files: src/**/*.{ts,tsx}
