name: Spell Check

on:
    workflow_dispatch:
    workflow_call:

jobs:
    run:
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
                  lfs: true

            - name: Run spell check
              uses: streetsidesoftware/cspell-action@v6
              with:
                  files: src/**/*.{ts,tsx}
